import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Set higher body limit for handling image uploads / base64 strings
  app.use(express.json({ limit: "15mb" }));

  // Initialize Gemini API
  const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });

  // Server capability check / API Health check
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok", message: "Server is online, meme generation ready." });
  });

  // AI MAGIC CAPTION ROTATION ENDPOINT
  app.post("/api/generate-captions", async (req, res): Promise<any> => {
    try {
      const { image, templateName, templateDescription, contextBonusPrompt } = req.body;

      if (!image && !templateDescription) {
        return res.status(400).json({ error: "Missing image data or template details to generate captions." });
      }

      // Prepare system-level guidance and humorous tone for the AI model
      let systemPrompt = `You are a legendary, high-IQ internet meme culture theorist and legendary meme lord.
Analyze the user's image and visual layout. Your objective is to create exactly 5 different, top-tier hilarious captions that perfectly match the picture's vibe, body language, or scenery.

CRITICAL INSTRUCTIONS:
- Generate EXACTLY 5 captions.
- Create multi-layer or single-layer text formats:
  - For two-section memes, separate top and bottom captions using a pipe symbol "|" (Example: "When you finally find the bug | It was a spelling error in a comment").
  - For single captions, do not include "|" (Example: "My last two brain cells during an exam").
- Tone can vary: self-deprecating humor, relatable programmer/office life jokes, modern Gen Z/millennial sarcasm, and cheeky observational thoughts. Make them incredibly witty, punchy, and current.
- Do NOT repeat the same punchlines or write generic answers like "This is awesome" or "What a day". Let your memes be incredibly funny, specific and relatable!
- Avoid boring explanations or offensive, hateful or NSFW output.

If the user specified a template named "${templateName || ''}" with description "${templateDescription || ''}", make sure to leverage its classic joke structure if relevant, but also generate fresh, creative reinventions.
${contextBonusPrompt ? `User also provided this custom theme or topic hint: "${contextBonusPrompt}". Integrate it creatively if possible!` : ""}`;

      let contents: any;
      const isRealImageUpload = image && !image.includes("image/svg+xml") && !image.includes("<svg");

      if (isRealImageUpload) {
        let mimeType = "image/jpeg";
        let rawData = image;

        // Process data URLs
        if (image.includes(";base64,")) {
          const parts = image.split(";base64,");
          mimeType = parts[0].split(":")[1] || "image/jpeg";
          rawData = parts[1];
        }

        // Sanitize mime type to avoid invalid formats
        if (!mimeType.includes("image/jpeg") && !mimeType.includes("image/png") && !mimeType.includes("image/webp")) {
          mimeType = "image/jpeg";
        }

        const imagePart = {
          inlineData: {
            mimeType: mimeType,
            data: rawData
          }
        };

        const textPart = {
          text: systemPrompt
        };

        contents = {
          parts: [imagePart, textPart]
        };
      } else {
        const contextText = `${systemPrompt}\n\n[Context Notice: Analyzing layout template "${templateName || 'Custom Template'}" - Description: "${templateDescription || 'Interactive layout with customizable top and bottom texts'}" - Please generate great text suggestions based on this context description]`;
        contents = {
          parts: [{ text: contextText }]
        };
      }

      console.log("Contacting Gemini for AI captions...");
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: contents,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.ARRAY,
            description: "A list of exactly 5 funny meme captions. Use '|' to separate top text from bottom text where appropriate.",
            items: {
              type: Type.STRING
            }
          }
        }
      });

      const responseText = response.text;
      if (!responseText) {
        throw new Error("No caption text generated by Google Gemini.");
      }

      let captions = JSON.parse(responseText.trim());
      if (!Array.isArray(captions)) {
        throw new Error("Gemini returned invalid caption format.");
      }

      // Final validation clean up
      captions = captions.slice(0, 5).map(cap => typeof cap === 'string' ? cap : String(cap));
      
      return res.json({ captions });

    } catch (apiError: any) {
      console.error("Gemini Caption Failure:", apiError);
      return res.status(500).json({ error: apiError?.message || "Internal Server Error during meme analysis." });
    }
  });

  // AI SPOTLIGHT PROMPT WRITER AND EXTRACTOR
  app.post("/api/generate-prompt", async (req, res): Promise<any> => {
    try {
      const { image, tweaks, templateName, templateDescription } = req.body;

      let systemPrompt = `You are an expert AI prompt engineer and professional creative director.
Your goal is to extract the visual structure, layout, core subject, background, lighting, and style from a reference image or context description, and rewrite it into a pristine, high-fidelity prompt for an AI Image Generator. 
You must incorporate any custom modifications or twists described by the user: "${tweaks || 'No specific tweaks requested, make it look cinematic and high resolution'}".

Output your response in a valid JSON format with these exact keys:
1. "extractedStyle": A brief summary of the extracted style and composition of the reference image.
2. "idealPrompt": A single, incredibly detailed, descriptive, high-fidelity prompt ready to be pasted into a Gemini/Imagen image generator. Include details about lighting, camera angle, textures, and composition.
3. "suggestedStylePreset": One specific aesthetic category (e.g. "Photorealistic", "Cyberpunk", "Oil Painting", "3D Render", "Retro Comic", "Vintage Vector").

Keep the tone expert, helpful, and highly descriptive.`;

      let contents: any;
      const isRealImageUpload = image && !image.includes("image/svg+xml") && !image.includes("<svg");

      if (isRealImageUpload) {
        let mimeType = "image/jpeg";
        let rawData = image;

        if (image.includes(";base64,")) {
          const parts = image.split(";base64,");
          mimeType = parts[0].split(":")[1] || "image/jpeg";
          rawData = parts[1];
        }

        if (!mimeType.includes("image/jpeg") && !mimeType.includes("image/png") && !mimeType.includes("image/webp")) {
          mimeType = "image/jpeg";
        }

        const imagePart = {
          inlineData: {
            mimeType: mimeType,
            data: rawData
          }
        };

        contents = {
          parts: [imagePart, { text: systemPrompt }]
        };
      } else {
        const textPrompt = `${systemPrompt}\n\n[Context: Generating prompt based on template "${templateName || 'Custom Template'}" - Description: "${templateDescription || 'Standard layout'}"]`;
        contents = {
          parts: [{ text: textPrompt }]
        };
      }

      console.log("Analyzing scene style and constructing optimal prompt...");
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: contents,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              extractedStyle: { type: Type.STRING },
              idealPrompt: { type: Type.STRING },
              suggestedStylePreset: { type: Type.STRING }
            },
            required: ["extractedStyle", "idealPrompt", "suggestedStylePreset"]
          }
        }
      });

      const responseText = response.text;
      if (!responseText) {
        throw new Error("No prompt data returned by Google Gemini.");
      }

      const promptData = JSON.parse(responseText.trim());
      return res.json(promptData);

    } catch (err: any) {
      console.error("Gemini Prompt Writer Failure:", err);
      return res.status(500).json({ error: err?.message || "Internal Server Error during prompt engineering." });
    }
  });

  // Integrate Vite Dev/Production pipelines
  if (process.env.NODE_ENV !== "production") {
    console.log("Serving in Development Mode (Vite Middleware Active)...");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    console.log("Serving in Production Mode...");
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`AI Meme Generator DevServer is running on port ${PORT}`);
  });
}

startServer().catch((err) => {
  console.error("FATAL: Failed to start the backend Express server:", err);
});
